language: c
#sudo: false # only for faster builds
script:
  - clang -coverage -O0 src/hello.c test/test.c -o test/testhello
  - ./test/testhello
  - gcov src/hello.c
  - cat hello.c.gcov
  - gcov src/hello.h test/test.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
